apiVersion: v2
name: open-gegevenslaag-chart
description: Generic Helm chart for deploying applications on Kubernetes
type: application
version: 1.0.0
home: https://github.com/maykinmedia/open-gegevenslaag-chart
maintainers:
  - name: maykinmedia
    email: info@maykin.nl

dependencies:
  - name: redis
    version: 17.3.14
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
  - name: common
    version: 2.27.0
    repository: https://charts.bitnami.com/bitnami
    tags:
    - bitnami-common
